version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:80"

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: social_media
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  db:
